# git-cliff configuration - generates CHANGELOG.md from commit messages
# Adjust `types` and `title` sections to match your commit message conventions


[changelog]
header = "Changelog"
body = """
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
		- {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
				{% if commit.breaking %}[**破坏性更改**] {% endif %}\
				{{ commit.message | upper_first }}\
{% endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
		## {{ group | striptags | trim | upper_first }}
		{% for commit in commits
		| filter(attribute="scope")
		| sort(attribute="scope") %}
				{{ self::print_commit(commit=commit) }}
		{%- endfor %}
		{% for commit in commits %}
				{%- if not commit.scope -%}
						{{ self::print_commit(commit=commit) }}
				{% endif -%}
		{% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | length != 0 %}
	## 贡献者

	感谢以下贡献者的贡献：

{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
	- @{{ contributor.username }}
{%- endfor -%}
{%- endif %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"
postprocessors = [{ pattern = "#([0-9]+)", replace = "([#${1}](https://github.com/ggchivalrous/yiyin/issues/${1}))"}]

[git]
commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->🚀 新增功能与优化" },
	{ message = "^fix", group = "<!-- 1 -->🐛 Bug 修复" },
	{ message = "^perf", group = "<!-- 0 -->🚀 新增功能与优化" },
	{ message = "^security", group = "<!-- 2 -->🔒 安全修复" },
	{ message = "^docs", group = "<!-- 3 -->📚 文档更新" },
	{ message = "^build", group = "<!-- 4 -->🔧 构建系统" },
	{ message = "^ci", group = "<!-- 4 -->🔧 构建系统" },
	{ message = "^revert", group = "<!-- 9 -->◀️ 回滚的功能" },
]
conventional_commits = true
conventional_line_breaks = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = false
remote = "origin"

[remote.github]
owner = "ggchivalrous"
repo = "yiyin"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
