export default {
  startTask: 'startTask',
  addTask: 'addTask',
  composite: 'composite',
  compositeFail: 'compositeFail',
  createBgImg: 'createBgImg',
  getConfig: 'getConfig',
  setConfig: 'setConfig',
  resetConfig: 'resetConfig',
  getFontList: 'getFontList',
  addFont: 'addFont',
  delFont: 'delFont',
  miniSize: 'miniSize',
  closeApp: 'closeApp',
  getExitInfo: 'getExitInfo',
  uploadExifImg: 'uploadExifImg',
  pathInfo: 'pathInfo',
  logoList: 'logoList',
  genTextImg: 'genTextImg',
  genMainImgShadow: 'genMainImgShadow',
  drainQueue: 'drainQueue',
  open: {
    selectPath: 'open:selectPath',
    dir: 'open:dir',
  },
  on: {
    createMask: 'on:createMask',
    taskStart: 'on:taskStart',
    faildTask: 'on:faildTask',
    progress: 'on:progress',
    composite: 'on:composite',
    assetsUpdate: 'on:assetsUpdate',
    genTextImg: 'on:genTextImg',
    genMainImgShadow: 'on:genMainImgShadow',
  },
};
